### ISSUE TITLE
[Chapter 3: SSI Using Indy, Aries and Ursa] Demo time

### ISSUE THREAD

**Issue by sfl0r3nz05** [cloudcompass/ToIPLabs#43]
Hi,

I am doing the EDX course "Introduction to Hyperledger Sovereign Identity Blockchain Solutions: Indy, Aries & Ursa". In chapter 3: SSI Using Indy, Aries and Ursa, Demo Time, appears a link that redirect to two demonstration. The first, "Mobile Agent Demonstration", use an Aries smartphone agent called Streetcred, however I can't find this agent, I installed another one called Trinsic Wallet (trinsic.id). Additionally, to perform the demonstration in the Trinsic Wallet menu you must change the network to "Sovrin Staging Network", in order to avoid a network error. 

I consider that this details must be provided.

Santiago.

**Comment by swcurran** [comment]
Thanks for the note.  You are right -- Streetcred has become Trinsic since the course was created.  We'll take a look through the materials and update them.  Sorry for the delay in our doing that.
