### ISSUE TITLE
Problem of running Hyperledger Indy, Aries, Ursa Agent Demonstration

### ISSUE THREAD

**Issue by 2017zhangyuxuan** [cloudcompass/ToIPLabs#85]
For this instruction `https://github.com/cloudcompass/ToIPLabs/blob/main/src/indy-material/nodejs/RunningLocally.md`, when I do the command `./manage build`, it failed. The error image like this.
![image](https://user-images.githubusercontent.com/43541108/143770118-89e0e823-d359-4077-a788-7caea1d3ae15.png)

I tried `pip install --upgrade pip`. But is didn't work. It seemed that pip was still old version. Can you give me some advice?

**Comment by 2017zhangyuxuan** [comment]
When I resolved above problems by upgradeing setuptools, I used the command `./manage up` and then it had another problem like this:
![image](https://user-images.githubusercontent.com/43541108/143973575-203bce4c-8fdd-4ede-a2f0-dbc99c206932.png)

**Comment by nebucaz** [comment]
@2017zhangyuxuan I also had the qemu core dump when trying to run the von-network on Apple Silicon M1. I ended up re-building the underlying docker image ([von-image](https://github.com/PSPC-SPAC-buyandsell/von-image)) for limux/arm64 architecture. See the discussion [here](https://github.com/bcgov/von-network/issues/182). You can run the von-network on Apple Silicon M1 (or Linux/arm64) by replacing the first line in the Dockerfile of von-network:

```
#FROM bcgovimages/von-image:node-1.12-4
FROM snel/von-image:node-1.12-4-arm64
```

which then points to my image of von-network compiled for arm64 architecture. You can create your own docker-image following the steps described in the [pull-request](https://github.com/PSPC-SPAC-buyandsell/von-image/pull/27)

**Comment by 2017zhangyuxuan** [comment]
@nebucaz Thanks a lot for answering. However, there is still an error. Can you show me the whole `pool.dockerfile` ?
![image](https://user-images.githubusercontent.com/43541108/144809487-bc352250-7c66-4fc4-b754-15a0565b3297.png)

**Comment by nebucaz** [comment]
@2017zhangyuxuan I'm sorry, my instructions are meant for the [von-network](https://github.com/bcgov/von-network#running-the-network-locally). The von-network is using the von-image:node-1.12 but here the von-image is used, which seems to be different. 

The base image used in pool.dockerfile is [bcgovimages/von-image:py35-1.6-8 ](https://hub.docker.com/layers/bcgovimages/von-image/py35-1.6-8/images/sha256-07ad74dcbf0570f4437f253d2c0b212f77a004c2ed3c68d4f454ecbc1f4da86f?context=explore). This image is more than 3 years old and uses amd64 architecture - maybe that's a problem. I'm currently working to compile the von-image on M1 - I'll keep you posted

**Comment by swcurran** [comment]
Sorry for being slow to answer this one. As @nebucaz correctly points out, this is a very old, locked in time demo that I should have retired.  Rather than trying to fix this, I've replaced the lab with a new one that uses the latest code is maintained far better than the one I had been using.

I'm going to close this issue as "too old to address", and you will see that the readme directs the user to a different, but similar lab.

**Comment by knagware9** [comment]
Indy agents giving errorr - container logs message as below-

> indy-agent@0.0.0 start /home/indy/nodejs
> node ./bin/www

wallet already exist, try to open wallet
wallet already exist, try to open wallet
{ IndyError: LedgerInvalidTransaction
    at Object.callback (/home/indy/nodejs/node_modules/indy-sdk/src/wrapIndyCallback.js:15:10)
  name: 'IndyError',
  message: 'LedgerInvalidTransaction',
  indyCode: 304,
  indyName: 'LedgerInvalidTransaction' }
