### ISSUE TITLE
mock BC Government service url not working in several browsers

### ISSUE THREAD

**Issue by jruizaranguren** [cloudcompass/ToIPLabs#92]
I'm trying the Issuing, Holding, Proving demo as part of LFS173x. In the step access to mock BC Government service at https://verified-email-authentication.vonx.io/, button `proceed` is not working. I just see a text label in multipe browsers (tried Firefox, Chrome, Brave and Edge).

**Comment by swcurran** [comment]
We're checking on it...

**Comment by swcurran** [comment]
Working again.  Thanks for the note.  Closing this issue.
