### ISSUE TITLE
 key error exception when running the Alice get a job lab

### ISSUE THREAD

**Issue by jruizaranguren** [cloudcompass/ToIPLabs#95]
I have completed the steps in the lab `Alice get a job lab`: https://github.com/cloudcompass/ToIPLabs/blob/main/docs/LFS173xV2/HelpAliceGetAJob.md

1. Degree credential is issued from faber to alice
2. Work credential can be issued from acme to alice
3. Degree proof can be requested from acme to alice

But in the third case, even I'm getting a `Acme | Proof = True` message, I also get an unhandled exception from the asyncio loop, as it is shown in the following image:

 ![image](https://user-images.githubusercontent.com/1499916/197552336-1a6aa82d-9345-44f5-96d7-fad7a1d5a9a2.png)

Any clue? Is it something related to how the keys of attributes are being built in faber.py#225?

I have copied the snippets of code as is from the lab.

**Comment by swcurran** [comment]
A PR was added to ACA-Py for this issue.  Do you have time @jruizaranguren to see if this resolves your issue?

PR: https://github.com/hyperledger/aries-cloudagent-python/pull/1990

Thanks!

**Comment by swcurran** [comment]
ACA-Py issue has been merged, fixing this issue. Closing.

**Comment by jruizaranguren** [comment]
Super, @swcurran. Thanks!
